backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "film" # Used in routes, e.g., /admin/collections/blog
    label: "Film" # Used in the UI
    folder: "src/content/film" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Synopsis", name: "synopsis", widget: "richtext" }
      - { label: "Cast", name: "cast", widget: "markdown" }
      - { label: "Crew", name: "crew", widget: "markdown" }
      - { label: "Directors", name: "directors", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Thumbnail Clip", name: "clip", widget: "file" }
